/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : string,
  'languageId' : string,
  'name' : string,
}
export interface Flashcard {
  'id' : string,
  'categoryId' : string,
  'exampleSentence' : string,
  'languageId' : string,
  'exampleTranslation' : string,
  'translation' : string,
  'targetWord' : string,
  'phonetic' : string,
}
export interface Highscore { 'username' : string, 'points' : bigint }
export interface Language {
  'id' : string,
  'code' : string,
  'flag' : string,
  'name' : string,
}
export interface LanguageProgress {
  'quizScores' : Array<bigint>,
  'languageId' : string,
  'totalXP' : bigint,
  'lessonsCompleted' : Array<string>,
}
export interface QuizQuestion {
  'id' : string,
  'categoryId' : string,
  'question' : string,
  'correctIndex' : bigint,
  'languageId' : string,
  'flashcardId' : string,
  'options' : Array<string>,
}
export interface UserProfile {
  'xp' : bigint,
  'username' : string,
  'badges' : Array<string>,
  'lastActiveDate' : bigint,
  'currentStreak' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllUserProgress' : ActorMethod<[], Array<[string, LanguageProgress]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[string], Array<Category>>,
  'getFlashcards' : ActorMethod<[string, string], Array<Flashcard>>,
  'getLanguages' : ActorMethod<[], Array<Language>>,
  'getLeaderboard' : ActorMethod<[], Array<Highscore>>,
  'getOrCreateProfile' : ActorMethod<[string], UserProfile>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getQuizQuestions' : ActorMethod<[string, string], Array<QuizQuestion>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProgress' : ActorMethod<[string], [] | [LanguageProgress]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordFlashcardViewed' : ActorMethod<[string, string, string], undefined>,
  'recordQuizScore' : ActorMethod<[string, string, bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProfile' : ActorMethod<[string], undefined>,
  'updateStreak' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];