/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LanguageProgress = IDL.Record({
  'quizScores' : IDL.Vec(IDL.Nat),
  'languageId' : IDL.Text,
  'totalXP' : IDL.Nat,
  'lessonsCompleted' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'xp' : IDL.Nat,
  'username' : IDL.Text,
  'badges' : IDL.Vec(IDL.Text),
  'lastActiveDate' : IDL.Int,
  'currentStreak' : IDL.Nat,
});
export const Category = IDL.Record({
  'id' : IDL.Text,
  'languageId' : IDL.Text,
  'name' : IDL.Text,
});
export const Flashcard = IDL.Record({
  'id' : IDL.Text,
  'categoryId' : IDL.Text,
  'exampleSentence' : IDL.Text,
  'languageId' : IDL.Text,
  'exampleTranslation' : IDL.Text,
  'translation' : IDL.Text,
  'targetWord' : IDL.Text,
  'phonetic' : IDL.Text,
});
export const Language = IDL.Record({
  'id' : IDL.Text,
  'code' : IDL.Text,
  'flag' : IDL.Text,
  'name' : IDL.Text,
});
export const Highscore = IDL.Record({
  'username' : IDL.Text,
  'points' : IDL.Nat,
});
export const QuizQuestion = IDL.Record({
  'id' : IDL.Text,
  'categoryId' : IDL.Text,
  'question' : IDL.Text,
  'correctIndex' : IDL.Nat,
  'languageId' : IDL.Text,
  'flashcardId' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllUserProgress' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, LanguageProgress))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([IDL.Text], [IDL.Vec(Category)], ['query']),
  'getFlashcards' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Flashcard)],
      ['query'],
    ),
  'getLanguages' : IDL.Func([], [IDL.Vec(Language)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(Highscore)], ['query']),
  'getOrCreateProfile' : IDL.Func([IDL.Text], [UserProfile], []),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getQuizQuestions' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(QuizQuestion)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProgress' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(LanguageProgress)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordFlashcardViewed' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'recordQuizScore' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProfile' : IDL.Func([IDL.Text], [], []),
  'updateStreak' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LanguageProgress = IDL.Record({
    'quizScores' : IDL.Vec(IDL.Nat),
    'languageId' : IDL.Text,
    'totalXP' : IDL.Nat,
    'lessonsCompleted' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'xp' : IDL.Nat,
    'username' : IDL.Text,
    'badges' : IDL.Vec(IDL.Text),
    'lastActiveDate' : IDL.Int,
    'currentStreak' : IDL.Nat,
  });
  const Category = IDL.Record({
    'id' : IDL.Text,
    'languageId' : IDL.Text,
    'name' : IDL.Text,
  });
  const Flashcard = IDL.Record({
    'id' : IDL.Text,
    'categoryId' : IDL.Text,
    'exampleSentence' : IDL.Text,
    'languageId' : IDL.Text,
    'exampleTranslation' : IDL.Text,
    'translation' : IDL.Text,
    'targetWord' : IDL.Text,
    'phonetic' : IDL.Text,
  });
  const Language = IDL.Record({
    'id' : IDL.Text,
    'code' : IDL.Text,
    'flag' : IDL.Text,
    'name' : IDL.Text,
  });
  const Highscore = IDL.Record({ 'username' : IDL.Text, 'points' : IDL.Nat });
  const QuizQuestion = IDL.Record({
    'id' : IDL.Text,
    'categoryId' : IDL.Text,
    'question' : IDL.Text,
    'correctIndex' : IDL.Nat,
    'languageId' : IDL.Text,
    'flashcardId' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllUserProgress' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, LanguageProgress))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([IDL.Text], [IDL.Vec(Category)], ['query']),
    'getFlashcards' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Flashcard)],
        ['query'],
      ),
    'getLanguages' : IDL.Func([], [IDL.Vec(Language)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(Highscore)], ['query']),
    'getOrCreateProfile' : IDL.Func([IDL.Text], [UserProfile], []),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getQuizQuestions' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(QuizQuestion)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProgress' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(LanguageProgress)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordFlashcardViewed' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'recordQuizScore' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProfile' : IDL.Func([IDL.Text], [], []),
    'updateStreak' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };